### ISSUE TITLE
A brief history of branch prediction

### ISSUE THREAD

**Issue by ykozw** [postdcc/translation_request#11]
# 翻訳リクエスト希望

## 記事URL（必須）
https://danluu.com/branch-prediction/

## 記事タイトル（必須）
A brief history of branch prediction

## 著者名
Dan Luu

## 著者連絡先
不明。Twitterは @danluu 。

## 選定理由
最近話題になった spectre、meltdownの原因となる投機実行の話であり、興味を惹かれる人は多いと思われるため。

**Comment by siminzhuo** [comment]
翻訳リクエストありがとうございました！
遅くなりましたが、こちらの翻訳記事を投稿させていただきました。
また気になる記事などあればリクエストいただけると幸いです。
今後ともPOSTDをよろしくお願いいたします！
