### ISSUE TITLE
Why Are Enterprises So Slow?

### ISSUE THREAD

**Issue by gotodeploy** [postdcc/translation_request#15]
# 翻訳リクエスト希望

## 記事URL（必須）

https://zwischenzugs.com/2018/10/02/why-are-enterprises-so-slow/

## 記事タイトル（必須）

Why Are Enterprises So Slow?

## 著者名

Ian Miell

## 著者連絡先

ian.miell@gmail.com
https://ian.meirionconsulting.com/

## 選定理由

これからスタートアップからエンタープライズ系に転職をしようとしている方の一助となるかと思います。読んでいると、どこの国の会社かなんて関係ないのだなと考えさせられました。

**Comment by Seiichi-Akiba** [comment]
翻訳リクエストありがとうございます！
内部にて検討させていただきます！
今後ともPOSTをよろしくお願いします
