### ISSUE TITLE
A 2017 Guide to Semantic Segmentation with Deep Learning

### ISSUE THREAD

**Issue by LouiS0616** [postdcc/translation_request#6]
# 翻訳リクエスト希望

## 記事URL（必須）

[http://blog.qure.ai/notes/semantic-segmentation-deep-learning-review](http://blog.qure.ai/notes/semantic-segmentation-deep-learning-review)

## 記事タイトル（必須）

A 2017 Guide to Semantic Segmentation with Deep Learning

## 著者名

Sasank Chilamkurthy

## 著者連絡先

prashant.warier@qure.ai

**Comment by mo-ry** [comment]
翻訳リクエストありがとうございました！
遅くなりましたが、本日こちらの翻訳記事を投稿させていただきました。
また気になる記事などあればリクエストいただけると幸いです。
今後ともPOSTDをよろしくお願いいたします！
