### ISSUE TITLE
Blameless PostMortems and a Just Culture

### ISSUE THREAD

**Issue by pomu0326** [postdcc/translation_request#7]
# 翻訳リクエスト希望

## 記事URL（必須）

https://codeascraft.com/2012/05/22/blameless-postmortems/

## 記事タイトル（必須）

Blameless PostMortems and a Just Culture

## 著者名

John Allspaw

## 選定理由

[ソフトウェアエンジニアリングにおける認知バイアス5つ](http://postd.cc/cognitive-biases-in-software-engineering/) にこの記事へのリンクがあり読んでみたかった。

## 備考

POSTD の翻訳記事、いつも参考にさせていただいています！
よろしくお願いします。

**Comment by mo-ry** [comment]
翻訳リクエストありがとうございました！
本日こちらの記事を投稿させて頂きました。
また気になる記事等あればリクエスト頂ければ幸いです。
今後ともPOSTDをよろしくお願いいたします！
