### ISSUE TITLE
A Million WebSockets and Go

### ISSUE THREAD

**Issue by syossan27** [postdcc/translation_request#8]
# 翻訳リクエスト希望

## 記事URL（必須）

https://medium.freecodecamp.org/million-websockets-and-go-cc58418460bb

## 記事タイトル（必須）

A Million WebSockets and Go

## 著者名

Sergey Kamardin
https://medium.freecodecamp.org/@gobwas

## 著者連絡先

gobwas@gmail.com

## 選定理由

ロシアの大手電子メール業者によるWebSocketとGoの知見が書かれており、非常に興味深い内容なのですが、自分の英語力では全てを読み解くことに限界を感じたため

## 備考

是非ともお願い致します

**Comment by AtsukiTak** [comment]
👍

**Comment by re-fort** [comment]
こちらに記載できていませんでしたが、すでに公開させていただいております！
リクエストを送っていただきありがとうございました:blush:
http://postd.cc/100%E4%B8%87%E5%9B%9E%E3%81%AEwebsocket%E6%8E%A5%E7%B6%9A%E3%81%A8go/
