### ISSUE TITLE
Recursive Make Considered Harmful

### ISSUE THREAD

**Issue by nagayasu-shinya** [postdcc/translation_request#9]
# 翻訳リクエスト希望

## 記事URL（必須）

http://aegis.sourceforge.net/auug97.pdf

## 記事タイトル（必須）

Recursive Make Considered Harmful

## 著者名

Peter Miller

## 著者連絡先

millerp@canb.auug.org.au

## 選定理由

Makefile は現在も広く使われているツールです。
大規模なプロジェクトでは再帰的makeは避けて非再帰的makeを使うことが推奨されていますが、実際の現場ではあまり意識されていないように思います。
そこで、再帰的makeの問題を提起した論文「Recursive Make Considered Harmful」をリクエストいたします。
これにより、再帰的makeの問題が周知されることを期待しております。

## 備考

Makefile については、オライリージャパンより電子書籍（PDF）が公開されております。
https://www.oreilly.co.jp/library/4873112699/

とくに再帰make についての言及は、下記のPDFファイルにあります。
https://www.oreilly.co.jp/library/4873112699/ch06.pdf

ちなみにですが、オライリーの原書は下記に公開されています。
http://www.oreilly.com/openbook/make3/book/index.csp

**Comment by re-fort** [comment]
こちら著者に翻訳許諾依頼のメールを投げているのですが、返答が現状ない状態です。。
いったんクローズさせていただき、進展があり次第、再度オープンさせていただきます。

**Comment by nagayasu-shinya** [comment]
そうなんですね、諒解しました.......
ありがとうございました！
